services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  dynamodb:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
